"""agent workflows and reliability

Revision ID: c57f8be7e15c
Revises: 20260823_0001
Create Date: 2026-08-23 03:56:16.551044
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c57f8be7e15c"
down_revision: Union[str, None] = "20260823_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cleanup_entries",
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_key", sa.String(length=220), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("pending", "succeeded", name="cleanupstate", native_enum=False),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_type", "resource_key", name="uq_cleanup_resource"),
    )
    op.create_index(
        op.f("ix_cleanup_entries_claimed_at"), "cleanup_entries", ["claimed_at"], unique=False
    )
    op.create_index(
        op.f("ix_cleanup_entries_document_id"), "cleanup_entries", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_cleanup_entries_next_attempt_at"),
        "cleanup_entries",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(op.f("ix_cleanup_entries_state"), "cleanup_entries", ["state"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=220), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("origin_correlation_id", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum("pending", "dispatched", "acked", name="outboxstate", native_enum=False),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("celery_task_id", sa.String(length=80), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_claimed_at"), "outbox_events", ["claimed_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_next_attempt_at"), "outbox_events", ["next_attempt_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_origin_correlation_id"),
        "outbox_events",
        ["origin_correlation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_outbox_events_state"), "outbox_events", ["state"], unique=False)
    op.create_index(op.f("ix_outbox_events_topic"), "outbox_events", ["topic"], unique=False)
    op.create_table(
        "mcp_access_tokens",
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_mcp_access_tokens_expires_at"), "mcp_access_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_mcp_access_tokens_user_id"), "mcp_access_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "workflow_runs",
        sa.Column("requested_by_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("document_ids", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("origin_correlation_id", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "running",
                "waiting_approval",
                "completed",
                "rejected",
                "insufficient",
                "failed",
                name="workflowstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("intent", sa.String(length=80), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("insufficient_evidence", sa.Boolean(), nullable=True),
        sa.Column("cited_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "requested_by_id", "idempotency_key", name="uq_workflow_run_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_workflow_runs_origin_correlation_id"),
        "workflow_runs",
        ["origin_correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_runs_requested_by_id"), "workflow_runs", ["requested_by_id"], unique=False
    )
    op.create_index(op.f("ix_workflow_runs_state"), "workflow_runs", ["state"], unique=False)
    op.create_table(
        "action_proposals",
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("previous_proposal_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "invalidated",
                "expired",
                "executed",
                "failed",
                name="proposalstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assignee", sa.String(length=200), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "critical", name="taskpriority", native_enum=False),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reasoning_summary", sa.String(length=1000), nullable=False),
        sa.Column("cited_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("canonical_payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("evidence_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_proposal_id"], ["action_proposals.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_run_id", "payload_hash", name="uq_proposal_run_payload_hash"),
        sa.UniqueConstraint("workflow_run_id", "version", name="uq_proposal_run_version"),
    )
    op.create_index(
        op.f("ix_action_proposals_expires_at"), "action_proposals", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_action_proposals_state"), "action_proposals", ["state"], unique=False)
    op.create_index(
        op.f("ix_action_proposals_workflow_run_id"),
        "action_proposals",
        ["workflow_run_id"],
        unique=False,
    )
    op.create_table(
        "extracted_findings",
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "finding_type",
            sa.Enum(
                "obligation",
                "deadline",
                "responsible_party",
                "risk",
                "required_action",
                name="findingtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("normalized_value", sa.String(length=500), nullable=True),
        sa.Column("responsible_party", sa.String(length=300), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("severity", sa.String(length=40), nullable=True),
        sa.Column("cited_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("stable_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_run_id", "stable_hash", name="uq_finding_run_hash"),
    )
    op.create_index(
        op.f("ix_extracted_findings_finding_type"),
        "extracted_findings",
        ["finding_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extracted_findings_workflow_run_id"),
        "extracted_findings",
        ["workflow_run_id"],
        unique=False,
    )
    op.create_table(
        "approval_decisions",
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("proposal_version", sa.Integer(), nullable=False),
        sa.Column("decided_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("approve", "reject", "edit", name="decisionkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("evidence_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("replacement_proposal_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["proposal_id"], ["action_proposals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["replacement_proposal_id"], ["action_proposals.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proposal_id", name="uq_decision_proposal"),
    )
    op.create_index(
        op.f("ix_approval_decisions_proposal_id"),
        "approval_decisions",
        ["proposal_id"],
        unique=False,
    )
    op.create_table(
        "workflow_tasks",
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("approval_decision_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assignee", sa.String(length=200), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "critical", name="taskpriority", native_enum=False),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "open", "in_progress", "completed", "cancelled", name="taskstate", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_decision_id"],
            ["approval_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("approval_decision_id"),
    )
    op.create_index(
        op.f("ix_workflow_tasks_proposal_id"), "workflow_tasks", ["proposal_id"], unique=True
    )
    op.create_index(op.f("ix_workflow_tasks_state"), "workflow_tasks", ["state"], unique=False)
    op.add_column("audit_events", sa.Column("causation_id", sa.String(length=64), nullable=True))
    op.add_column("audit_events", sa.Column("thread_id", sa.UUID(), nullable=True))
    op.add_column("audit_events", sa.Column("dedupe_key", sa.String(length=220), nullable=True))
    op.create_index(
        op.f("ix_audit_events_causation_id"), "audit_events", ["causation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_thread_id"), "audit_events", ["thread_id"], unique=False)
    op.create_unique_constraint("uq_audit_events_dedupe_key", "audit_events", ["dedupe_key"])
    op.alter_column("citations", "chunk_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("citations_chunk_id_fkey"), "citations", type_="foreignkey")
    op.create_foreign_key(
        "fk_citations_chunk_id", "citations", "chunks", ["chunk_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "document_revisions",
        sa.Column("origin_correlation_id", sa.String(length=64), nullable=True),
    )
    op.execute(
        "UPDATE document_revisions "
        "SET origin_correlation_id = 'legacy-migration-' || id::text "
        "WHERE origin_correlation_id IS NULL"
    )
    op.alter_column("document_revisions", "origin_correlation_id", nullable=False)
    op.create_index(
        op.f("ix_document_revisions_origin_correlation_id"),
        "document_revisions",
        ["origin_correlation_id"],
        unique=False,
    )
    op.add_column(
        "documents", sa.Column("source_content_sha256", sa.String(length=64), nullable=True)
    )
    op.execute(
        "UPDATE documents AS document "
        "SET source_content_sha256 = revision.content_sha256 "
        "FROM document_revisions AS revision "
        "WHERE revision.document_id = document.id "
        "AND revision.revision_number = 1 "
        "AND document.source_content_sha256 IS NULL"
    )
    op.execute(
        "UPDATE documents "
        "SET source_content_sha256 = md5(id::text) || md5('localguard:' || id::text) "
        "WHERE source_content_sha256 IS NULL"
    )
    op.alter_column("documents", "source_content_sha256", nullable=False)
    # Phase 1 allowed separate active document rows for the same actor and
    # original bytes.  Quarantine later duplicates deterministically before
    # introducing the active-row uniqueness rule.  Their revisions and private
    # files remain referenced so a downgrade can restore the exact legacy rows.
    op.execute(
        """
        CREATE TEMPORARY TABLE localguard_c57_duplicate_documents (
            document_id UUID PRIMARY KEY,
            canonical_document_id UUID NOT NULL,
            previous_state VARCHAR(20) NOT NULL
        ) ON COMMIT DROP
        """
    )
    op.execute(
        """
        WITH ranked AS (
            SELECT
                id,
                state::text AS previous_state,
                first_value(id) OVER (
                    PARTITION BY created_by_id, source_content_sha256
                    ORDER BY created_at, id
                ) AS canonical_document_id,
                row_number() OVER (
                    PARTITION BY created_by_id, source_content_sha256
                    ORDER BY created_at, id
                ) AS duplicate_ordinal
            FROM documents
            WHERE deleted_at IS NULL
        )
        INSERT INTO localguard_c57_duplicate_documents (
            document_id,
            canonical_document_id,
            previous_state
        )
        SELECT id, canonical_document_id, previous_state
        FROM ranked
        WHERE duplicate_ordinal > 1
        """
    )
    op.execute(
        """
        INSERT INTO audit_events (
            occurred_at,
            actor_id,
            action,
            resource_type,
            resource_id,
            outcome,
            correlation_id,
            detail,
            id,
            causation_id,
            thread_id,
            dedupe_key
        )
        SELECT
            CURRENT_TIMESTAMP,
            NULL,
            'migration.document_duplicate_quarantined',
            'document',
            duplicate.document_id,
            'quarantined',
            'migration-c57-document-dedupe',
            json_build_object(
                'canonical_document_id', duplicate.canonical_document_id::text,
                'previous_state', duplicate.previous_state,
                'private_source_retained', true
            ),
            md5(
                'migration-c57-document-dedupe:' || duplicate.document_id::text
            )::uuid,
            NULL,
            NULL,
            'migration:c57:document-dedupe:' || duplicate.document_id::text
        FROM localguard_c57_duplicate_documents AS duplicate
        ON CONFLICT (id) DO UPDATE SET
            occurred_at = EXCLUDED.occurred_at,
            outcome = EXCLUDED.outcome,
            detail = EXCLUDED.detail,
            dedupe_key = EXCLUDED.dedupe_key
        """
    )
    op.execute(
        """
        UPDATE documents AS document
        SET
            state = 'deleted',
            deleted_at = CURRENT_TIMESTAMP
        FROM localguard_c57_duplicate_documents AS duplicate
        WHERE document.id = duplicate.document_id
        """
    )
    op.create_index(
        "uq_document_actor_content_active",
        "documents",
        ["created_by_id", "source_content_sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column("question_jobs", sa.Column("request_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "question_jobs", sa.Column("origin_correlation_id", sa.String(length=64), nullable=True)
    )
    op.execute(
        "UPDATE question_jobs "
        "SET request_hash = md5(id::text) || md5(question), "
        "origin_correlation_id = 'legacy-migration-' || id::text "
        "WHERE request_hash IS NULL OR origin_correlation_id IS NULL"
    )
    op.alter_column("question_jobs", "request_hash", nullable=False)
    op.alter_column("question_jobs", "origin_correlation_id", nullable=False)
    op.create_index(
        op.f("ix_question_jobs_origin_correlation_id"),
        "question_jobs",
        ["origin_correlation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    orphan_citation_count = int(
        op.get_bind().scalar(sa.text("SELECT count(*) FROM citations WHERE chunk_id IS NULL")) or 0
    )
    if orphan_citation_count:
        raise RuntimeError(
            "Downgrade blocked: "
            f"{orphan_citation_count} citation snapshot(s) reference deleted chunks. "
            "Export them with `python -m localguard_api.cli export-orphan-citations "
            "--output <path>`, "
            "then explicitly purge them before retrying the downgrade."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_jobs_origin_correlation_id"), table_name="question_jobs")
    op.drop_column("question_jobs", "origin_correlation_id")
    op.drop_column("question_jobs", "request_hash")
    # This revision briefly shipped with a global constraint-backed index before
    # the active-row partial index was finalized.  Accept either head shape so
    # already-upgraded development databases remain reversible.
    op.execute("DROP INDEX IF EXISTS uq_document_actor_content_active")
    op.execute("ALTER TABLE documents DROP CONSTRAINT IF EXISTS uq_document_actor_content")
    op.execute("DROP INDEX IF EXISTS uq_document_actor_content")
    op.drop_column("documents", "source_content_sha256")
    op.execute(
        """
        UPDATE documents AS document
        SET
            state = COALESCE(audit.detail ->> 'previous_state', 'failed'),
            deleted_at = NULL
        FROM audit_events AS audit
        WHERE audit.action = 'migration.document_duplicate_quarantined'
          AND audit.resource_type = 'document'
          AND audit.resource_id = document.id
          AND audit.outcome = 'quarantined'
        """
    )
    op.execute(
        """
        UPDATE audit_events
        SET outcome = 'reverted'
        WHERE action = 'migration.document_duplicate_quarantined'
          AND outcome = 'quarantined'
        """
    )
    op.drop_index(
        op.f("ix_document_revisions_origin_correlation_id"), table_name="document_revisions"
    )
    op.drop_column("document_revisions", "origin_correlation_id")
    op.drop_constraint("fk_citations_chunk_id", "citations", type_="foreignkey")
    op.create_foreign_key(
        op.f("citations_chunk_id_fkey"), "citations", "chunks", ["chunk_id"], ["id"]
    )
    op.alter_column("citations", "chunk_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint("uq_audit_events_dedupe_key", "audit_events", type_="unique")
    op.drop_index(op.f("ix_audit_events_thread_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_causation_id"), table_name="audit_events")
    op.drop_column("audit_events", "dedupe_key")
    op.drop_column("audit_events", "thread_id")
    op.drop_column("audit_events", "causation_id")
    op.drop_index(op.f("ix_workflow_tasks_state"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_proposal_id"), table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index(op.f("ix_approval_decisions_proposal_id"), table_name="approval_decisions")
    op.drop_table("approval_decisions")
    op.drop_index(op.f("ix_extracted_findings_workflow_run_id"), table_name="extracted_findings")
    op.drop_index(op.f("ix_extracted_findings_finding_type"), table_name="extracted_findings")
    op.drop_table("extracted_findings")
    op.drop_index(op.f("ix_action_proposals_workflow_run_id"), table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_state"), table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_expires_at"), table_name="action_proposals")
    op.drop_table("action_proposals")
    op.drop_index(op.f("ix_workflow_runs_state"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_requested_by_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_origin_correlation_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_mcp_access_tokens_user_id"), table_name="mcp_access_tokens")
    op.drop_index(op.f("ix_mcp_access_tokens_expires_at"), table_name="mcp_access_tokens")
    op.drop_table("mcp_access_tokens")
    op.drop_index(op.f("ix_outbox_events_topic"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_state"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_origin_correlation_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_next_attempt_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_claimed_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_cleanup_entries_state"), table_name="cleanup_entries")
    op.drop_index(op.f("ix_cleanup_entries_next_attempt_at"), table_name="cleanup_entries")
    op.drop_index(op.f("ix_cleanup_entries_document_id"), table_name="cleanup_entries")
    op.drop_index(op.f("ix_cleanup_entries_claimed_at"), table_name="cleanup_entries")
    op.drop_table("cleanup_entries")
    # ### end Alembic commands ###
